const enum PredictionPhrase {
  Device = 'In some federal states and cities, there are collective containers for smaller electrical appliances, in the others, one has to go to a depot to deliver the scrap or wait for the pick-up service',
  Special = 'In some cities, there are pick-up services available for collecting such waste, but in other cities you have to personally take it to the recycling depot. Energy-saving lamps, LED and batteries could be also disposed of at drugstores and hardware stores.',
  Bulky = 'In many cities, there are specific schedules for picking up the bulky waste. It is best to ask the municipality in your area.',
  Clothing = 'Old clothing containers in which one can dispose of the unwanted clothes are seen at every corner across Germany.',
  Bottle = '\n If it is a plastic bottle: ' +
    '- with a recycle sign ♼ then recycle it at grocery stores and even get 25 cents per bottle \n' +
    '- without a sign then throtit to the yellow 🌕 trash bin for plastic and light-weight packaging \n' +
    'If it is a glass bottle: \n' +
    '- with a pfand in the receipt then recycle it at grocery stores and get around 8 cents.per bottle \n' +
    '- without a sign then throw it to respective dedicated containers for bottles (🔘️️, 🦋 or 🍂 or)',
  Bio = 'Compostable kitchen and garden waste (e.g. coffee and tea dregs, fruit and vegetables remains, eggshells, leaves) go to the black black ⚫️ (sometimes brown 🍂) trash bin (usually marked "BSR")',
  Packing = 'Light-weight packaging, i.e. all packaging which are not made of glass or paper (for example aluminum foil, plastic bags, tins, yoghurt cups, juice and milk cartons/Tetra-packs, plastic bottles, coffee packs) goes to yellow bins 🌕',
  Paper = 'Paper waste and cardboard (for example, paper bags, newspapers, catalogs, writing paper, cartons, cigarette packs) go to blue 🦋 (green 📗) paper bins. Very old/stained paper ought to be put in the black ⚫️ (gray 📁) residual waste bin and juice and milk cartons/Tetra-packs in the yellow 🌕 sack/bin.',
  NonRecyclable = 'Residual waste or household waste and all other types of waste that cannot be recycled (for example, porcelain, hygiene articles, dirty packaging, shoes, household items, vacuum cleaner bags, diapers, cigarette butts, window glasses) go to the black ⚫️ (gray 📁) residual waste bin',
  Person = 'Use the app for something else',
  Transport = 'Transport requires detailed investigation on how to recycle it.',
  Animal = 'Well... Animals should be burred at dedicated animal cemeteries',
}

export const PREDICTION_TO_PHRASE: ReadonlyMap<string, string> = new Map([
  ['laptop', PredictionPhrase.Device],
  ['cell phone', PredictionPhrase.Device],
  ['tablet', PredictionPhrase.Device],
  ['person', PredictionPhrase.Person],
  ['bicycle', PredictionPhrase.Transport],
  ['car', PredictionPhrase.Transport],
  ['motorcycle', PredictionPhrase.Transport],
  ['airplane', PredictionPhrase.Transport],
  ['bus', PredictionPhrase.Transport],
  ['train', PredictionPhrase.Transport],
  ['truck', PredictionPhrase.Transport],
  ['boat', PredictionPhrase.Transport],
  ['traffic light', PredictionPhrase.Device],
  ['fire hydrant', PredictionPhrase.Bulky],
  ['stop sign', PredictionPhrase.Bulky],
  ['parking meter', PredictionPhrase.Bulky],
  ['bench', PredictionPhrase.Bulky],
  ['bird', PredictionPhrase.Animal],
  ['cat', PredictionPhrase.Animal],
  ['dog', PredictionPhrase.Animal],
  ['horse', PredictionPhrase.Animal],
  ['sheep', PredictionPhrase.Animal],
  ['cow', PredictionPhrase.Animal],
  ['elephant', PredictionPhrase.Animal],
  ['bear', PredictionPhrase.Animal],
  ['zebra', PredictionPhrase.Animal],
  ['giraffe', PredictionPhrase.Animal],
  ['backpack', PredictionPhrase.Clothing],
  ['umbrella', PredictionPhrase.NonRecyclable],
  ['tie', PredictionPhrase.Clothing],
  ['suitcase', PredictionPhrase.Clothing],
  ['frisbee', PredictionPhrase.Packing],
  ['skis', PredictionPhrase.Bulky],
  ['snowboard', PredictionPhrase.Bulky],
  ['sports ball', PredictionPhrase.NonRecyclable],
  ['kite', PredictionPhrase.NonRecyclable],
  ['baseball bat', PredictionPhrase.NonRecyclable],
  ['baseball glove', PredictionPhrase.NonRecyclable],
  ['skateboard', PredictionPhrase.Bulky],
  ['snowboard', PredictionPhrase.Bulky],
  ['tennis racket', PredictionPhrase.Bulky],
  ['bottle', PredictionPhrase.Bottle],
  ['wine glass', PredictionPhrase.Bottle],
  ['cup', PredictionPhrase.NonRecyclable],
  ['fork', PredictionPhrase.NonRecyclable],
  ['knife', PredictionPhrase.NonRecyclable],
  ['spoon', PredictionPhrase.NonRecyclable],
  ['bowl', PredictionPhrase.NonRecyclable],
  ['banana', PredictionPhrase.Bio],
  ['apple', PredictionPhrase.Bio],
  ['sandwich', PredictionPhrase.Bio],
  ['orange', PredictionPhrase.Bio],
  ['broccoli', PredictionPhrase.Bio],
  ['carrot', PredictionPhrase.Bio],
  ['hot dog', PredictionPhrase.Bio],
  ['pizza', PredictionPhrase.Bio],
  ['donut', PredictionPhrase.Bio],
  ['cake', PredictionPhrase.Bio],
  ['chair', PredictionPhrase.Bulky],
  ['couch', PredictionPhrase.Bulky],
  ['potted plant', PredictionPhrase.Bio],
  ['bed', PredictionPhrase.Bulky],
  ['dinning table', PredictionPhrase.Bulky],
  ['toilet', PredictionPhrase.Bulky],
  ['tv', PredictionPhrase.Device],
  ['mouse', PredictionPhrase.Device],
  ['remote', PredictionPhrase.Device],
  ['keyboard', PredictionPhrase.Device],
  ['microwave', PredictionPhrase.Device],
  ['oven', PredictionPhrase.Bulky],
  ['toaster', PredictionPhrase.Device],
  ['sink', PredictionPhrase.Bulky],
  ['refrigerator', PredictionPhrase.Bulky],
  ['book', PredictionPhrase.Paper],
  ['clock', PredictionPhrase.NonRecyclable],
  ['vase', PredictionPhrase.NonRecyclable],
  ['scissors', PredictionPhrase.NonRecyclable],
  ['teddy bear', PredictionPhrase.NonRecyclable],
  ['hair drier', PredictionPhrase.NonRecyclable],
  ['tooth brush', PredictionPhrase.NonRecyclable],
])
